AWSTemplateFormatVersion: '2010-09-09'
Description: Driver template to deploy lambda function
Parameters:
  project:
    Type: String
    Default: bottest-ai
    Description:  Project Name
  env:
    Type: String
    Default: prod
    AllowedValues: [prod, dev, qa, stag]
    Description:  Environment Name
  app:
    Type: String
    Default: app
    Description:  Application Name
  s3ArtifactPath:
    Type: String
    Default: "https://bottest-ai-app-prod-us-east-1-122253718099.s3.amazonaws.com/code/cfn/services"
    Description: Artifact Bucket Path
Resources:
  lambdaFunction:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/lambda/lambda-app.yml"
      Parameters:
        project: !Ref project
        app: !Ref app
        env: !Ref env
        privateSubnet01: !GetAtt vpc.Outputs.privateSubnetA
        privateSubnet02: !GetAtt vpc.Outputs.privateSubnetB
        securityGroup: !GetAtt securityGroup.Outputs.webSecurityGroup
        dbHostPoint: !GetAtt rds.Outputs.dBEndpoint