AWSTemplateFormatVersion: '2010-09-09'
Description: Driver template to deploy lambda function
Parameters:
  project:
    Type: String
    Default: bottest-ai
    Description:  Project Name
  env:
    Type: String
    Default: prod
    AllowedValues: [prod, dev, qa, stag]
    Description:  Environment Name
  app:
    Type: String
    Default: app
    Description:  Application Name
  s3ArtifactPath:
    Type: String
    Default: "https://bottest-ai-app-prod-us-east-1-122253718099.s3.amazonaws.com/code/cfn/services"
    Description: Artifact Bucket Path
Resources:
  lambdaFunction:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${s3ArtifactPath}/lambda/lambda-app.yml"
      Parameters:
        project: !Ref project
        app: !Ref app
        env: !Ref env
        privateSubnet01: !Select [4, !Split [",", !GetAtt vpc.Outputs.SubnetIds]]
        privateSubnet02: !Select [5, !Split [",", !GetAtt vpc.Outputs.SubnetIds]]
        lambdaSecurityGroup: !GetAtt securityGroup.Outputs.sgLambdaId
        ecrRepositoryUri: !GetAtt ecrRepository.Outputs.ecrRepositoryUri
        dbHostPoint: !GetAtt rdsInstance.Outputs.dBEndpoint
        slackToken: !Ref slackToken
        openaiApiKey: !Ref openaiApiKey
        jwksUrl: !Ref jwksUrl
        environment: !Ref environment
        clerkApiKey: !Ref clerkApiKey
        dBUsername: !Ref dBUsername
        dBPassword: !Ref dBPassword
        dbName: mydb
Outputs:
  lambdaFunction:
    Value: !Ref lambdaFunction
    Export:
      Name: !Sub "${project}-${env}-${app}-lambdaFunction-${AWS::Region}"